### ISSUE TITLE
Home Assistant reports sensor errors for this component

### ISSUE THREAD

**Issue by shadowano** [sockless-coding/panasonic_cc#104]
Running latest version, v1.0.35.

` File "/config/custom_components/panasonic_cc/sensor.py", line 142, in state
    return round(self._api.daily_energy,2)
TypeError: type NoneType doesn't define __round__ method`

![image](https://user-images.githubusercontent.com/3582807/227134576-fea2dccd-894c-41a2-92c3-887b0ad743a8.png)

![image](https://user-images.githubusercontent.com/3582807/227135171-e47123c8-182e-4b73-86ca-94312525c1d1.png)

**Comment by codyc1515** [comment]
I believe this was solved?

**Comment by shadowano** [comment]
Might be, can't see it in logs now.

**Comment by blissi** [comment]
Hi,
I have v1.0.38 and still have this issue.
I don't think so, but could this be a reason why my Home Assistant regularly (every few days) crashes? That is the last message that I can see in _home-assistant.log.1_

**Comment by codyc1515** [comment]
Doubt that very much but I have added a check for this scenario in any case.
