### ISSUE TITLE
Panasonic Comfort Cloud stopped showing state, sensors and other details within HA. 

### ISSUE THREAD

**Issue by djmaxim1981** [sockless-coding/panasonic_cc#139]
Hi Team HA,
Can you please help look into this integration? It has stopped working for the past 1 week, noticeably after the recent HA upgrade. I am still able to turn on/off the aircond via HA but the state doesn't change, nor do the temp sensors work. I've attempted to remove and re-integrate Comfort Cloud to HA, but same issue appears again. FYI - I am on  v1.0.37
![image](https://github.com/sockless-coding/panasonic_cc/assets/112385832/d07a1138-789c-4e69-8ccd-c3ab60c78e09)

Logger: homeassistant.config_entries
Source: config_entries.py:557
First occurred: 2:00:22 PM (1 occurrences)
Last logged: 2:00:22 PM

Error unloading entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 102, in async_unload_entry
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by djmaxim1981** [comment]
[PLEASE ADVISE!! --- IS THIS A FIX?]


The error message indicates that there is an issue with the panasonic_cc custom component for Home Assistant. The component is trying to unload an entry, but it is passing a coroutine directly to the asyncio.wait() function instead of a task. This is no longer allowed in Python 3.11, and it is causing the error.

To fix the error, you need to wrap the coroutine in a task before passing it to asyncio.wait(). You can do this using the asyncio.create_task() function. For example, the following code shows how to fix the error in the async_unload_entry() function:


async def async_unload_entry(self, hass):
    tasks = [asyncio.create_task(task()) for task in self._tasks]
    await asyncio.wait(tasks)

This code will create a task for each coroutine in the _tasks list and then wait for all of the tasks to complete before returning. This should fix the error and allow the component to unload properly.

**Comment by codyc1515** [comment]
I believe this should be working for you again now?

**Comment by djmaxim1981** [comment]
U

> I believe this should be working for you again now?




Unfortunately, I'm still faced with the same problem. And I also updated to the  'latest' release v1.0.38.

Issues 
- Unable to change any state 
- Unable to set temp
- No data showing on thermostat.

Only function that works is the Power On & Off which also has no state.

ComfortCloud app is working just fine.




2024-01-10 14:27:38.486 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 102, in async_unload_entry
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
2024-01-10 14:27:38.507 WARNING (MainThread) [py.warnings] /usr/src/homeassistant/homeassistant/config_entries.py:576: RuntimeWarning: coroutine 'ConfigEntries.async_forward_entry_unload' was never awaited
  return False

2024-01-10 14:28:16.023 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Set PC Room AC mode cool
2024-01-10 14:28:18.289 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Error trying to get device cbe54a820054db040668d0ca46f8f9e74d2732574f10eb19c7087e3a6537bf2d state, probably expired token, trying to update it...
2024-01-10 14:28:20.003 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Failed to renew token for device cbe54a820054db040668d0ca46f8f9e74d2732574f10eb19c7087e3a6537bf2d, giving up for now

**Comment by djmaxim1981** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:557
First occurred: 2:27:38 PM (1 occurrences)
Last logged: 2:27:38 PM

Error unloading entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 102, in async_unload_entry
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by codyc1515** [comment]
What AC is this? Aquarea?

Please try remove the config entry and try set it up again - looks like there is an issue with the token also.

**Comment by djmaxim1981** [comment]
> What AC is this? Aquarea?
> 
> Please try remove the config entry and try set it up again - looks like there is an issue with the token also.

 - I'm using Panasonic CS-XPU13XKH-1A (R32)
 - Can you advise how I can remove the "config entry"? I've already removed the integration and re-added it back into HA, but no joy. Same error faced.

**Comment by djmaxim1981** [comment]
Just pasting this here incase it helps. (/homeassistant/custom_components/panasonic_cc/config_flow.py


"""Config flow for the Panasonic Comfort Cloud platform."""
import asyncio
from typing import Any, Dict, Optional
import logging

from aiohttp import ClientError
from async_timeout import timeout
import voluptuous as vol

from homeassistant import config_entries
from homeassistant.const import CONF_USERNAME, CONF_PASSWORD
from homeassistant.core import callback

from . import DOMAIN as PANASONIC_DOMAIN

from .panasonic import PanasonicApiDevice

from .const import (
    KEY_DOMAIN, 
    TIMEOUT, 
    CONF_FORCE_OUTSIDE_SENSOR, 
    CONF_ENABLE_DAILY_ENERGY_SENSOR, 
    DEFAULT_ENABLE_DAILY_ENERGY_SENSOR)

_LOGGER = logging.getLogger(__name__)

@config_entries.HANDLERS.register("panasonic_cc")
class FlowHandler(config_entries.ConfigFlow):
    """Handle a config flow."""

    VERSION = 1
    CONNECTION_CLASS = config_entries.CONN_CLASS_CLOUD_POLL

    @staticmethod
    @callback
    def async_get_options_flow(config_entry):
        """Get the options flow for this handler."""
        return PanasonicOptionsFlowHandler(config_entry)

    async def _create_entry(self, username, password):
        """Register new entry."""
        # Check if ip already is registered
        for entry in self._async_current_entries():
            if entry.data[KEY_DOMAIN] == PANASONIC_DOMAIN:
                return self.async_abort(reason="already_configured")

        return self.async_create_entry(title="", data={
            CONF_USERNAME: username, 
            CONF_PASSWORD: password, 
            CONF_FORCE_OUTSIDE_SENSOR: False,
            CONF_ENABLE_DAILY_ENERGY_SENSOR: DEFAULT_ENABLE_DAILY_ENERGY_SENSOR
            })

    async def _create_device(self, username, password):
        """Create device."""
        from . import pcomfortcloud
        try:

            api = pcomfortcloud.Session(username, password, verifySsl=False)
            devices = await self.hass.async_add_executor_job(api.get_devices)
            if not devices:
                return self.async_abort(reason="No devices")
        except asyncio.TimeoutError:
            return self.async_abort(reason="device_timeout")
        except ClientError:
            _LOGGER.exception("ClientError")
            return self.async_abort(reason="device_fail")
        except Exception:  # pylint: disable=broad-except
            _LOGGER.exception("Unexpected error creating device")
            return self.async_abort(reason="device_fail")

        return await self._create_entry(username, password)

    async def async_step_user(self, user_input=None):
        """User initiated config flow."""
        if user_input is None:
            return self.async_show_form(
                step_id="user", data_schema=vol.Schema({
                    vol.Required(CONF_USERNAME): str,
                    vol.Required(CONF_PASSWORD): str
                    })
            )
        return await self._create_device(user_input[CONF_USERNAME], user_input[CONF_PASSWORD])

    async def async_step_import(self, user_input):
        """Import a config entry."""
        username = user_input.get(CONF_USERNAME)
        if not username:
            return await self.async_step_user()
        return await self._create_device(username, user_input[CONF_PASSWORD])

class PanasonicOptionsFlowHandler(config_entries.OptionsFlow):
    """Handle Panasonic options."""

    def __init__(self, config_entry):
        """Initialize Panasonic options flow."""
        self.config_entry = config_entry

    async def async_step_init(
        self, user_input: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Manage Panasonic options."""
        if user_input is not None:
            return self.async_create_entry(title="", data=user_input)

        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_FORCE_OUTSIDE_SENSOR,
                        default=self.config_entry.options.get(
                            CONF_FORCE_OUTSIDE_SENSOR, False
                        ),
                    ): bool,
                    vol.Optional(
                        CONF_ENABLE_DAILY_ENERGY_SENSOR,
                        default=self.config_entry.options.get(
                            CONF_ENABLE_DAILY_ENERGY_SENSOR, DEFAULT_ENABLE_DAILY_ENERGY_SENSOR
                        ),
                    ): bool,
                }
            ),
        )

**Comment by djmaxim1981** [comment]
Hi @codyc1515 
Can you advise how I can remove the "config entry"? I've already removed the integration and re-added it back into HA, but no joy. Same error faced.

**Comment by djmaxim1981** [comment]
Issue is now resolved for me. Comfort Cloud is working as it should be. Thank you !
